name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main", "fix/sphinx-docs-pipeline"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Set up Python and install dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install sphinx myst-parser

      # Step 3: Set PYTHONPATH to src/ and generate .rst files
      - name: Set PYTHONPATH to src
        run: |
          echo "PYTHONPATH=$PWD/src" >> $GITHUB_ENV
          sphinx-apidoc -o docs/ src/

      # Step 4: Reset PYTHONPATH to docs/ and build the HTML files
      - name: Reset PYTHONPATH to docs and build HTML
        run: |
          echo "PYTHONPATH=$PWD/docs" >> $GITHUB_ENV
          make -C docs html

      # Step 5: Upload the HTML files to GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
