name: "Sphinx: Render docs"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install sphinx myst-parser

    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$PWD/src" >> $GITHUB_ENV  # Set the src/ directory to PYTHONPATH

    - name: Generate .rst files
      run: sphinx-apidoc -o docs/ src/

    - name: Reset Python path
      run: |
        echo "PYTHONPATH=$PWD/docs" >> $GITHUB_ENV

    - name: Build HTML documentation
      run: make clean html

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
